services:
  backend_api:
    build: ./api
    container_name: backend_api_container
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    develop:
      watch:
      - action: sync
        path: ./client
        target: ./app/src/client
        ignore: 
        - ./app/node_modules
      - action: rebuild
        path: ./client 
    
      

#   web:
#     build: .
#     ports:
#       - "8080:8080"
#   db:
#     image: "mysql"
#     environment: 
#       MYSQL_ROOT_PASSWORD: password
#     volumes:
#       - db-data:/foo

# volumes:
#   db-data:

